version: "3.9"

services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
    - redpanda start
    - --overprovisioned
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --node-id 0
    - --check=false
    - --kafka-addr 0.0.0.0:9092
    - --advertise-kafka-addr redpanda:9092
    - --pandaproxy-addr 0.0.0.0:8082
    - --advertise-pandaproxy-addr redpanda:8082
    - --set redpanda.enable_transactions=true
    - --set redpanda.enable_idempotence=true
    - --set redpanda.auto_create_topics_enabled=true
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082

  faust:
    build:
      context: ./faust
      network: host
    container_name: faust
    depends_on:
      - redpanda

  producer:
    build:
      context: ./pythonproducer
      network: host
    container_name: producer
    depends_on:
      - redpanda

  kafkasink:
    build:
      context: ./kafkaconnect/s3_integration
      network: host
    container_name: kafkasink
    depends_on:
      - redpanda
      - faust
      - producer